[theme]
primaryColor = "#004990"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#EEF2F7"
textColor = "#1A2733"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
